
  /*******************************************************************
  * loadTeamsPlayer.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package com.example.piets.hockeymanagement;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import java.util.*;


public class loadTeamsPlayer
{

    static final String SERVICE_NAME = "loadTeamsPlayer";


    private static loadTeamsPlayer ourInstance = new loadTeamsPlayer();

    private loadTeamsPlayer(  )
    {
    }

    public static loadTeamsPlayer getInstance()
    {
        return ourInstance;
    }




    
    public Object playersList(String teamId)
    {
        Object[] args = new Object[]{teamId};
        return Backendless.CustomService.invoke( SERVICE_NAME, "playersList", args, Object.class );
    }
    
    public void playersListAsync(String teamId, AsyncCallback<Object> callback)
    {
        Object[] args = new Object[]{teamId};
        Backendless.CustomService.invoke( SERVICE_NAME, "playersList", args, Object.class, callback);
    }
    
}
