
  /*******************************************************************
  * loadTeamsAddRelation.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package com.example.piets.hockeymanagement;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import java.util.*;


public class loadTeamsAddRelation
{

    static final String SERVICE_NAME = "loadTeamsAddRelation";


    private static loadTeamsAddRelation ourInstance = new loadTeamsAddRelation();

    private loadTeamsAddRelation(  )
    {
    }

    public static loadTeamsAddRelation getInstance()
    {
        return ourInstance;
    }




    
    public Object setUserTeams(String teamName, String objectId)
    {
        Object[] args = new Object[]{teamName, objectId};
        return Backendless.CustomService.invoke( SERVICE_NAME, "setUserTeams", args, Object.class );
    }
    
    public void setUserTeamsAsync(String teamName, String objectId, AsyncCallback<Object> callback)
    {
        Object[] args = new Object[]{teamName, objectId};
        Backendless.CustomService.invoke( SERVICE_NAME, "setUserTeams", args, Object.class, callback);
    }

    public void setUserTeamsAsync(String teamName, String userId) {
    }

}
